FROM rocker/shiny-verse:4.4.1

LABEL MAINTAINER Thiago Britto-Borges "thiago.brittoborges@uni-heidelberg.de"

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:criu/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    software-properties-common \
    sudo \
    criu \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libfftw3-dev \
    libpq-dev \
    libglpk-dev \
    libbz2-dev \
    liblzma-dev \
    strace \
    && rm -rf /var/lib/apt/lists/*

RUN useradd app \
    && mkdir /app \
    && chown app /app

ENV RENV_VERSION "1.0.7"

RUN R -e "remotes::install_github('rstudio/renv@v$RENV_VERSION')"
