FROM rocker/verse:4.2.1
RUN apt-get update -y && apt-get install -y  zlib1g-dev  make libcurl4-openssl-dev  libpq-dev  libxml2-dev  libicu-dev  make  libicu-dev zlib1g-dev  git libssl-dev libcurl4-openssl-dev  libcurl4-openssl-dev libssl-dev  libssl-dev make libcurl4-openssl-dev  git libgit2-dev libssl-dev libcurl4-openssl-dev  git  make zlib1g-dev  libicu-dev make pandoc  libssl-dev libcurl4-openssl-dev  libssl-dev  pandoc  libicu-dev zlib1g-dev libssl-dev make pandoc libcurl4-openssl-dev  libpng-dev  pandoc libicu-dev make  libxml2-dev make libcurl4-openssl-dev  libicu-dev make libxml2-dev pandoc  libicu-dev libssl-dev libxml2-dev libcurl4-openssl-dev  libicu-dev make zlib1g-dev pandoc  libxml2-dev pandoc  libfreetype6-dev libfribidi-dev libharfbuzz-dev libfontconfig1-dev pandoc libicu-dev libjpeg-dev libpng-dev libtiff-dev zlib1g-dev libssl-dev make libxml2-dev libcurl4-openssl-dev  git libgit2-dev libssl-dev make libcurl4-openssl-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
